name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and Push Docker Image
        run: |
          docker build -t ghcr.io/prakashkumar09031991/k8s-cicd-demo:latest .
          docker push ghcr.io/prakashkumar09031991/k8s-cicd-demo:latest

      - name: Update Kubernetes manifests
        run: |
          sed -i "s|ghcr.io.*|ghcr.io/prakashkumar09031991/k8s-cicd-demo:latest|g" k8s/deployment.yaml
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git commit -am "Update image version"
          git push
